version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre-build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands: 
      - echo build Docker image on `data`
      - cd src
      - docker build -t breakout-room-3-todo-image: latest .
      - docker tag breakout-room-3-todo-image: latest 962804699607.dkr.ecr.us-west-2.amazonaws.com/breakout-room-3-repo:latest
  post-build:
    commands:
      - echo build Docker iamge complete `date`
      - echo push latest Docker images to ECR...
      - docker push 962804699607.dkr.ecr.us-west-2.amazonaws.com/breakout-room-3-repo:latest
