version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre-build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands: 
      - echo build Docker image on `data`
      - cd src
      - docker build -t <image name>: latest .
      - docker tag <image name>: latest <ECR repository URI>:latest
  post-build:
    commands:
      - echo build Docker iamge complete `date`
      - echo push latest Docker images to ECR...
      - docker push <ECR repository URI>:latest
